"""v1

Revision ID: 0d36c4772520
Revises: bdb00f5e9e8b
Create Date: 2022-09-14 23:01:26.059227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d36c4772520'
down_revision = 'bdb00f5e9e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_acesso_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('acesso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_acesso_usuario')
    # ### end Alembic commands ###
