"""v0

Revision ID: bdb00f5e9e8b
Revises: 
Create Date: 2022-09-14 19:53:55.439438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdb00f5e9e8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_dominio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm_dominio', sa.Text(), nullable=True),
    sa.Column('tp_dominio', sa.Text(), nullable=True),
    sa.Column('origem_dominio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_dados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dados', sa.JSON(), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['tb_dominio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('senha', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['tb_dominio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_usuario')
    op.drop_table('tb_dados')
    op.drop_table('tb_dominio')
    # ### end Alembic commands ###
